### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by Daveawb** [syhol/mrcolor#5]
Hey Si,

Just having some ideas for us to rework this.
### Color
- Should have default colour, e.g. "#FFFFFF" configurable.
- Shouldn't require colour properties through constructor
- Have colours/attributes set via a builder interface
### Color Pallet
- Holds a collection of Color objects
- Ability to find, insert, query and sort Color objects
- Output array of hex values
- Output JSON of hex values
### Extensions
- Extensions need to be made more generic and class agnostic
- One extension interface for both Pallet and Color classes

**Comment by syhol** [comment]
Ahoy hoy chopper.

Will sort out priorities tomorrow or something, for now here are my thoughts...

### Color

I think it would be best to set a default color in an instance of a builder, rather than messing with the global state of the Color class. 

The constructor has a default empty array so nothing is required, but if given an array we run it through all the formats to see if its got any useful values to help determine the color.

And yes im very interested in building an awesome builder and factory. I would imagine the builder would have a fluent interface to build and perform a call on the factory that would create and configure the object(s) Color/ColorPallet

### Color Pallet

Love the idea for the color pallet, collections could be really powerful. The ability to query for a subset of a collection, then apply modifications that subset... very cool. Return array of hex/json of hex just sounds like an opportunity to build a good support for operations like 

``` php
$collection->pluck('hex')
json_encode($collection->pluck('hex'))
```

Or if we return generic vector collection objects from standard operations 

``` php
$collection->pluck('hex')->toArray()
$collection->pluck('hex')->toJson()
assert($collection instanceof MrColor\ColorPallet)
assert($collection->pluck('hex') instanceof MrColor\Collection)
assert($collection->pluck('hex')->toArray() === ['#ffaaff'])
```

Or best of both worlds, use a different method to return the values wrapped in a collection

``` php
assert($collection->pluckThen('hex') instanceof MrColor\Collection)
assert($collection->pluck('hex') === ['#ffaaff'])
```

But it seems like overkill/over-engineered. Just a thought.

And just food for thought:

``` php
$hexCodes = $collection->map(function ($color) { return $color->hex; })
$quiteRed = function ($color) { return $color->red > 150; };
$quiteRedColors = $collection->filter($quiteRed)
```

### Extensions

The original thinking behind the extensions was to make the experience feel more like Carbon or Mockery, where there is one facade and everything is built in. Now my knowledge of OOP has grown, I feel less of a need to pack everything into 1 object. The single responsibility principle seems abused here. The color object should be a data model for a color value, with loose coupling to other objects for format syncing, and that's it. Functionality like the old extensions can go in decorators or high level facades without adding weight to our data model. Running with that idea, is an interface or bespoke mechanism for extensions really needed? I think not, maybe just recommendations on how to extend using OOP techniques.

### Formats

It just needs some love and thought. The idea is good the execution could do with a little work.

### Contact

I got a new phone number so email it to the address listed on your github profile.

**Comment by Daveawb** [comment]
Hey hey Hat Abusing Monkey Chopper,

### Color

> I think it would be best to set a default color in an instance of a builder, rather than messing with the global state of the Color class.

If we were to go down a builder route it just would not be necessary, the Color class' interface would never be exposed to a developer until the builder returns either a Color object or a ColorPallet instance. Building anything in the constructor seems unnecessary when we will need either dedicated build methods or a generic component attachment structure. If we DI anything into Color it should be extending / enabling functionality not providing it.

### Color Palllet

> Love the idea for the color pallet, collections could be really powerful. The ability to query for a subset of a collection, then apply modifications that subset... very cool. Return array of hex/json of hex just sounds like an opportunity to build a good support for operations like.

Spot on, this was exactly my thinking. I was thinking back to the time I needed to output a range of colours based on a percentage value and realised that a collection would have been a far easier way to do it.

### Extensions

I get why they were part of the original, I don't think they're needed either in their current format, just wasn't sure you'd want to get rid of them.

What could be useful is some form of implementation specific extension. Very much similar to `Illuminate\Auth\Guard` that will accept an `extend` method call passing a closure where an object is built and passed back that handles the inner workings of the auth system.

``` php
MrColor::extend(function() 
{
    // Decorate the Color instance
    return new ColorDecorator(new Color);

    // Or some other complex setup
}
```

### Formats

Thinking about this Formatters would ideally be decorators. I talked above about how we could potentially allow 3rd party extensions. Using a Formatter should be as easy or could potentially have a dedicated method.

``` php
MrColor::format(FormatterOne::class);
MrColor::format([FormatterOne::class, FormatterTwo::class]);
```

**Comment by syhol** [comment]
Going to look at this more tonight.

I'm happy to lose the value in the constructor, but not sure if I want to inject extensions or not, I'm in two minds about it. I would be fairly happy injecting the formats though, as it makes sense, as its a true composition dependency.

Looking like your using a MrColor class to implement laravels facade pattern. Thats cool as long as its working with a builder instance behind the scenes. could be nice to see some

``` php
MrColor::red(20)->green(50)->alpha(0.9)->get()
MrColor::make(['red' => 20, 'green' => 50, 'alpha' => 0.9])
```

Talk tonight

##### Made some edits at 10AM

**Comment by Daveawb** [comment]
`MrColor` is the builder instance. It would build and return either a single colour or a collection of colours. With a fluent interface like you've described above it could do quite a bit.

Including building a pallet from a single colour very much like Google's Material Design colour specs (https://www.google.co.uk/design/spec/style/color.html).

``` php
$colour = MrColor::red(20)
    ->green(50)
    ->get();

assert($colour instanceof MrColor\Color::class);
assert( (string) $colour == '#143200' );

$pallet = $colour->createPallet(); // Assume this is the primary color (500)

assert($pallet instanceof MtColor\Pallet::class);
```

Now we have a single colour object that we built a pallet from.

Another idea: we could put in a pallet transformation layer abstracting the pallet build.

``` php
$from = MrColor::green(10)->red(10)->get();
$mid = MrColor::green(10)->red(10)->get();
$to = MrColor::green(10)->red(10)->get();

$pallet = $from->transformer(PalletRangeTransformer::class)
    ->range(0, 50)
    ->apply($mid)
    ->range(50, 100)
    ->apply($mid, $to);
```

I guess that the transformer method would return a `MrColor\Pallet` collection instance with the transformer applied to it. At each point `apply` is called it'll execute the configured settings and add to the collection.

**Comment by syhol** [comment]
The library API example you gave looks beautiful, I hope we can implement it in a smart manner. When you say "collection instance with the transformer applied to it" (bottom of your comment) is this going back to the extensions topic?

Also if you use `\MrColor` statically I would like to be able to swap out the instance for testing

``` php
MrColor::setInstance(Mockery::mock('MrColor\Builder'));
```

**Comment by Daveawb** [comment]
> Also if you use \MrColor statically I would like to be able to swap out the instance for testing

I guess I'm just using the statics as examples right now. I don't think it'd be good to use any statics in the core build but as a facade it'd be good. That way we can keep everything testable without needing to put code into the core specifically for unit testing.

I don't think extensions in their current guise work that great. The idea is sound and I like that method a lot but we can be a little cleverer about it for sure.

I think our next steps would be better if we organised our thoughts a little better so we can build up a spec wish list, then spin it out over releases. What do you think?

**Comment by syhol** [comment]
Write the spec, and have a general idea of the class structure and object relationships we want to create. 

New namespace /MrColor instead of /SyHolloway/MrColor as I'm not keen on the vendor namespace being my username any more, if people fork it or contribute to it, its kinda weird.

Formats can stay the same for this release, so I think the goal is to focus on 3 things:
- Object creation
- Extensions and Extending functionality
- Collection / Pallets

Rather ironically, I believe extensions are more important to the core and should have high priority, but if we are implementing extensions in collections too, it would make sense to have collections in place first.

As for the object builder, as long as we keep in mind we need to keep the API open to builders, I believe its less of a priority (although still required for a 1.0.0 release)

**Comment by Daveawb** [comment]
> New namespace /MrColor instead of /SyHolloway/MrColor

Haha yes, it is a bit weird! Suggest we move from PSR-1 to PSR-4.

> Rather ironically, I believe extensions are more important to the core and should have high priority

Any examples? I can't (at the moment) see why we wouldn't bake a lot of the functionality provided by some of the extensions into the core.

> As for the object builder, as long as we keep in mind we need to keep the API open to builders, I believe its less of a priority (although still required for a 1.0.0 release)

In my mind at the moment, we would only ever expose three API's the base builder being the primary one.

**MrColor**
Build up a colour and retrieve it. In true builder fashion this is the core API that is a convenience layer to producing complex `Color` objects.

**MrColor\Color**
Manipulate a generated `Color` (optionally build a Pallet from it).

**MrColor\Pallet**
Generated from a single root `Color` instance through a transformer.

**Comment by syhol** [comment]
PSR4 away! Woop!

What i meant to say was an extension system/schema/plan not necessarily the extensions themselves. Open closed principal and all. Designed early on, because i would really like to see the core stay nimble, and we will naturally want to grow the functionality.

Although on the flip side of that, we may not know what an extension needs access to, or what functionality an extension would need.

At the end of the day as long as the 3 public APIs are flexible enough, i guess extensions shouldn't be that important.

Wow look at that, you just witnessed me taking a 180. 

Alright it can go in the backlog.

As i mentioned before, ide like a standard factory api as well as the builder, but would be willing to leave it out of the public API if it can accept dumb/simple input (essentially a parse string to color method)

**Comment by Daveawb** [comment]
Rough outline on how the Color classes would be built

![mrcolor](https://cloud.githubusercontent.com/assets/4409005/8863955/fcde1120-3194-11e5-86cc-97604365025e.jpg)

**Comment by syhol** [comment]
inspiration: http://www.colorhexa.com/

**Comment by syhol** [comment]
Thinking about moving this into a github group. thoughts?

**Comment by Daveawb** [comment]
I think that's not a bad idea at all. What shall we call ourselves? :-)

**Comment by Daveawb** [comment]
Btw, I'm in Chicago all week so I doubt I'll get much done this week :-(

**Comment by syhol** [comment]
Well I'm in the middle of a re-brand to "syhol" (see http://syhol.io) so would be nice to incorporate that some how, but I'm currently in the habit of just sticking "way" on the end of stuff (e.g. awbway). 

I'm also super busy in the next few weeks, and can only spare an hour here and there.

Chicago eh? very exciting! business or holiday?

**Comment by Daveawb** [comment]
Business unfortunately :-(

I was thinking something without either of our personal stuff included.
Maybe a namespace that we can release tools and apps to that we both work
on? Also how would you feel about moving mrcolor way from Hutchhouse
branding as well?

**Comment by syhol** [comment]
Remove Hutchhouse branding for the 2.0 - release that's fine. 

As for the namespace, I get what your talking about but have no preference for a name.

Something with choppers in could be fun ;). but honestly I don't mind.

**Comment by Daveawb** [comment]
I like CodeMonkeys :-)

**Comment by syhol** [comment]
Could do, a bit popular already though:

![image](https://cloud.githubusercontent.com/assets/642428/9036442/8766d498-39d9-11e5-97a0-aeee9348bec8.png)

**Comment by Daveawb** [comment]
Meh ok, MonkeyChoppers would be amusing. Have a good think!

**Comment by Daveawb** [comment]
CodeChimps, LeagueOfChimps (LOC), ArmHairChoppers

**Comment by syhol** [comment]
LeagueOfChimps sounds great, kind of a play on the PHP "League of Extraordinary Packages" by Sturgeon and co.

**Comment by syhol** [comment]
Please change your remotes to point to my new username syhol. thanks.

**Comment by Daveawb** [comment]
No problem. Thanks.

**Comment by syhol** [comment]
I'm seriously looking at League Of Chimps. Want me to create the org?

**Comment by Daveawb** [comment]
Do it if you like it!
